ci:
  autoupdate_schedule: monthly
  autofix_commit_msg: "ci: [pre-commit.ci] auto fixes [...]"
  autoupdate_commit_msg: "ci: [pre-commit.ci] autoupdate"
  autofix_prs: true
  autoupdate_branch: ''
  submodules: false

# default_language_version:
#   python: python3.11

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-docstring-first
      - id: end-of-file-fixer
        exclude: typings
      - id: trailing-whitespace
        exclude: typings
      - id: mixed-line-ending

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.253"
    hooks:
      - id: ruff

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.300
    hooks:
    - id: pyright
      additional_dependencies: ["numpy>=1.21", "opencv-python"]
